export const ACCESS_TOKEN = "access_token"
export const REFRESH_TOKEN = "refresh_token"
// export const BASE_URL = process.env.REACT_APP_BE_URL || "http://localhost:3002"
export const BASE_URL = process.env.REACT_APP_BE_URL || "http://10.124.69.43:3002"
export const MINIO_PUBLIC_URL = process.env.MINIO_PUBLIC_URL || "http://10.124.64.125:19000/demo/"